version: "3"
services:
  app:
    build: .
    volumes:
      - ./logs:/var/log
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./db:/var/lib/mongodb
