version: "3"
services:
  app:
    build: .
    volumes:
      - logs:/var/log
    ports:
      - "${BGEXPLORER_PORT}:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    volumes:
      - mongodata:/data/db

volumes:
   mongodata:
   logs:
